import base64
import sys

import click

from requestfile.ast import (
    Argument,
    Command,
    Comment,
    Header,
    IncludedFile,
    QuotedValue,
    RawData,
    Requestfile,
    Requestline,
)
from requestfile.printing import print_requestfile


@click.command(
    name="convert-from-curl",
    context_settings=dict(
        ignore_unknown_options=True,
        allow_extra_args=True,
    ),
)
@click.option("--basic", "auth_type", flag_value="basic", default=True)
@click.option("-b", "--cookie", "cookies", multiple=True)
@click.option("--data-ascii", multiple=True)
@click.option("--data-binary", multiple=True)
@click.option("--data-raw", multiple=True)
@click.option("--data-urlencode", multiple=True)
@click.option("-d", "--data", multiple=True)
@click.option("--digest", "auth_type", flag_value="digest")
@click.option("-F", "--form", multiple=True)
@click.option("-G", "--get", is_flag=True)
@click.option("-H", "--header", "headers", metavar="<header/@file>", multiple=True)
@click.option("--json", metavar="<data>")
@click.option("-e", "--referer", metavar="<URL>")
@click.option("-X", "--request", "request_method", metavar="<method>")
@click.option("--resolve", metavar="<[+]host:port:addr[,addr]...>", multiple=True)
@click.option("--url-query", metavar="<data>", multiple=True)
@click.option("--url", "url_options", metavar="<url>", multiple=True)
@click.option("-A", "--user-agent", metavar="<name>")
@click.option("-u", "--user", metavar="<user:password>")
@click.argument("url")
# @click.option("--variable", metavar="<%name=text/@file>")
# TODO: support --expand-* options as well, for variables
@click.pass_context
def cmd_convert_from_curl(
    ctx,
    auth_type,
    cookies,
    data_ascii,
    data_binary,
    data_raw,
    data_urlencode,
    data,
    form,
    get,
    headers,
    json,
    referer,
    request_method,
    resolve,
    url_query,
    url_options,
    user_agent,
    user,
    url,
):
    """Create a Requestfile from a curl command"""

    # if "=" in cookie:
    #     pass  # Cookie string: "NAME1=VALUE1; NAME2=VALUE2"
    # else:
    #     pass  # Load cookies from file

    # All the --data{,-ascii,-binary} options are either @paths or raw data
    # --data-raw does not interpret @prefix

    if get is not False:
        raise ValueError("--get is not supported, use --url-query instead")

    # ----------------------------------------------------------------

    print("Extra arguments will be ignored:", ctx.args, file=sys.stderr)

    # ----------------------------------------------------------------

    rqf = Requestfile()
    _add_preamble_comment(rqf)
    _add_requestline(rqf, request_method, url, url_options)
    _add_request_params(rqf, url_query)
    _set_user_agent(rqf, user_agent)
    _set_authorization(rqf, auth_type, user)
    _add_cookies(rqf, cookies)
    _add_request_headers(rqf, headers)
    _add_request_data(rqf, data)
    _add_request_data(rqf, data_ascii)
    _add_request_data(rqf, data_binary)
    _add_request_data_raw(rqf, data_raw)
    _add_request_data_urlencode(rqf, data_urlencode)

    print_requestfile(rqf)


def _add_preamble_comment(rqf):
    rqf.preamble.append(Comment("Generated by requestfile from CURL command"))
    # TODO: include the original cURL command as well?
    # TODO: include instructions for sending the requestfile similarly
    #       to what was done with cURL?
    rqf.preamble.append(RawData(""))  # Blank line


def _add_requestline(rqf, method, url, url_options):
    if len(url_options) > 0:
        raise ValueError("The --url option is not supported")

    rqf.requestline = Requestline.from_method_and_url(method or "GET", url)


def _set_user_agent(rqf: Requestfile, user_agent: str | None):
    if user_agent is None:
        return
    rqf.headers.append(Header("User-Agent", user_agent))


def _set_authorization(rqf: Requestfile, auth_type: str | None, user: str | None):
    # TODO: rewrite this once we add first-class support for passing
    # authentication information
    if user is None:
        return
    if auth_type is None:
        auth_type = "basic"
    match auth_type:
        case "basic":
            auth_value = base64.b64encode(user.encode()).decode()
        case _:
            raise ValueError(f"{auth_type} authentication is not supported")
    rqf.headers.append(Header("Authorization", f"{auth_type} {auth_value}"))


def _add_request_headers(rqf, headers):
    for header in headers:
        # `Header:` -> unset internally set header
        # `Header;` -> header with no value
        # `@filename` -> load headers from file

        if header.startswith("@"):
            # Load headers from file
            rqf.headers.append(
                Command("headers", [Argument(None, IncludedFile(header[1:]))])
            )

        elif ":" in header:
            raw_key, raw_val = header.split(":", 1)
            rqf.headers.append(Header(raw_key.strip(), raw_val.strip()))

        else:
            raise ValueError(f"Malformed header: {header}")


def _add_cookies(rqf, cookies):
    for cookie_string in cookies:
        if "=" in cookie_string:
            for cookie_spec in cookie_string.split(";"):
                cookie_spec = cookie_spec.strip()
                name, value = cookie_spec.split("=", 1)
                rqf.headers.append(
                    Command(
                        "cookie",
                        [
                            Argument(None, QuotedValue(name)),
                            Argument(None, QuotedValue(value)),
                        ],
                    )
                )

        else:
            # Load cookies from file
            rqf.headers.append(
                Command("cookies", [Argument(None, IncludedFile(cookie_string))])
            )


def _add_request_params(rqf, param_specs):
    for param_spec in param_specs:
        pass


def _add_request_data(rqf, data_specs):
    for spec in data_specs:
        if spec.startswith("@"):
            rqf.body.append(
                Command("include", [Argument(None, IncludedFile(spec[1:]))])
            )
        else:
            rqf.body.append(RawData(spec))


def _add_request_data_raw(rqf, data_specs):
    for spec in data_specs:
        rqf.body.append(RawData(spec))


def _add_request_data_urlencode(rqf, data_specs):
    # content -> raw, urlencoded
    # =content -> raw, urlencoded. Strips the '='
    # name=content -> %field name content
    # @filename -> %include <filename
    # name@filename -> %field name <filename
    pass
